### ISSUE TITLE
NullPointerException org.apache.logging.log4j.Logger.error(String) in CLI

### ISSUE THREAD

**Issue by paulaescfer** [forcedotcom/dataloader#1208]
Hi!
I have a problem running dataloader from command line in Windows. When I try to run the process.bat I get the following error:

java.lang.NullPointerException: Cannot invoke "org.apache.logging.log4j.Logger.error(String)" because "com.salesforce.dataloader.util.AppUtil.logger" is null
        at com.salesforce.dataloader.util.AppUtil.setConfigurationsDir(AppUtil.java:312)
        at com.salesforce.dataloader.util.AppUtil.initializeAppConfig(AppUtil.java:140)
        at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:87)
        at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:72)

![image](https://github.com/user-attachments/assets/0b0d4a25-f8be-4144-9253-758a4908a663)

I have reinstalled java and also dataloader, but I still get the same error.

Attached is the process-conf.xml document hiding confidential information.

Do you know what could be happening?
[process-conf_issue.txt](https://github.com/user-attachments/files/16507244/process-conf_issue.txt)

Thanks!

**Comment by ashitsalesforce** [comment]
Hi @paulaescfer , it seems that you are invoking the following command:

`process.bat <DL installation folder> <bean id>`

Try instead
`process.bat <DL configuration folder containing process-conf.xml, config.properties, and log4j2j.properties> <bean id>`

For example,
`process.bat C:\Users\paulaescfer\dataloader_v62.0.0\v62.0.0\configs upsertAccount`

**Comment by paulaescfer** [comment]
hi @ashitsalesforce!

I tried what you suggested, but I keep getting the same error, am I doing something wrong?

![image](https://github.com/user-attachments/assets/3a1849de-bb3f-43b8-9545-d6a85d0bf4aa)

![image](https://github.com/user-attachments/assets/5c3d0352-e2d1-4bf9-aaf1-d1136bd7e058)

Thank you very much!

**Comment by ashitsalesforce** [comment]
Hi @paulaescfer , looking at the code I see that the cause is likely masked by NullPointerException thrown because Log4j logger is not initialized when initializing the configuration. I have changed the code to avoid using logger when initializing the configuration and have attached it for you to try and capture the output once again. Hopefully it will get us closer to the root cause.

You can also try installing Data Loader in a folder other than the folder in which it was extracted from. Lastly, check if your folder path has a special character such as a space character in it. If so, Data Loader may have a bug that is not processing it correctly.

Here is the data loader with the code change to not use logger when initializing config:
[dataloader_v62.0.0.zip](https://github.com/user-attachments/files/16530951/dataloader_v62.0.0.zip)

MD5 (dataloader_v62.0.0.zip) = 6364d483cc1690df084932b8b7f9ac9c

**Comment by paulaescfer** [comment]
Hi @ashitsalesforce!

It works!!!

Thank you so much!!

**Comment by ashitsalesforce** [comment]
Hi @paulaescfer , that's great to hear. Can you share the changes you made to make it work?

**Comment by paulaescfer** [comment]
Hi @ashitsalesforce !

I didn't have to make any changes, I just installed the new version you sent me in the previous post and when I ran it it worked.

Thank you very much for all the support :)

**Comment by ashitsalesforce** [comment]
That's good to hear. Thanks for your help in troubleshooting the issue.
