### ISSUE TITLE
Salesforce DataLoader CLI v45.0.0 - NullPointerException in initConfig

### ISSUE THREAD

**Issue by daveb-501commons** [forcedotcom/dataloader#179]
The new version of DataLoader v45.0.0 just released is throwing a NullPointerException when calling from the CommandLine

Java JDK Installed: jdk-11.0.2
Windows 10 Machine
 
Here is thread talking about the scenario
https://salesforce.stackexchange.com/questions/254408/nullpointerexception-processing-xml-configuration-for-salesforce-data-loader-cli/254523#254523
 
I've used the CLI before quite a bit but w/ the new v45 can't get past the error.
 
I'm using the Sample files provided and calling
 
process C:\dataloader\v45.0.0\samples\test\ csvAccountExtractProcess
 
2019-03-19 15:01:30,568 ERROR [csvAccountExtract] controller.Controller <init> (Controller.java:125) - Exception happened in initConfig:
java.lang.NullPointerException
        at java.base/java.util.Arrays.stream(Arrays.java:5614)
        at com.salesforce.dataloader.controller.Controller.getConfigDirFromArgMap(Controller.java:133)
        at com.salesforce.dataloader.controller.Controller.<init>(Controller.java:123)
        at com.salesforce.dataloader.controller.Controller.getInstance(Controller.java:269)
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:117)
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:107)
        at com.salesforce.dataloader.process.ProcessRunner.main(ProcessRunner.java:266)
2019-03-19 15:01:30,571 FATAL [csvAccountExtract] process.ProcessRunner topLevelError (ProcessRunner.java:251) - Unable to run process csvAccountExtract
java.lang.NullPointerException
        at java.base/java.util.Arrays.stream(Arrays.java:5614)
        at com.salesforce.dataloader.controller.Controller.getConfigDirFromArgMap(Controller.java:133)
        at com.salesforce.dataloader.controller.Controller.<init>(Controller.java:123)
        at com.salesforce.dataloader.controller.Controller.getInstance(Controller.java:269)
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:117)
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:107)
        at com.salesforce.dataloader.process.ProcessRunner.main(ProcessRunner.java:266)

I'll start debugging the code but thought I'd post to see if anyone has any thoughts.

-Dave

**Comment by langzi0** [comment]
Did the change https://github.com/forcedotcom/dataloader/commit/392159a559b4fc1d1a2bea5599a9b385b96719dc fix the problem?   Try to download zip again.

**Comment by xbiansf** [comment]
Can you download the updated release V45 again?  We had a commit to fix NullPointerException already. 
https://github.com/forcedotcom/dataloader/commit/392159a559b4fc1d1a2bea5599a9b385b96719dc

**Comment by daveb-501commons** [comment]
@xbiansf 

Still having same exception

Downloaded again and confirmed jar file updated because is bigger now and have a more recent date

Modified Date: Tuesday, ‎February ‎26, ‎2019, ‏‎3:23:32 PM
Size: 14.3 MB (15,075,325 bytes)

**Comment by xbiansf** [comment]
Have you set up all the password, etc?  We need more details of your config info to further investigate this.

**Comment by alina133** [comment]
I'm also stuck with the same issue.

I've installed the Data Loader 6 hours ago. And the error is the same. It seems like the dataloader-45.0.0-uber.jar wasn't updated with commit to fix NullPointerException yet.

Could you please check it? 
Thank you!

**Comment by xbiansf** [comment]
We will check this. Thanks for the feedback.

**Comment by jjangsfdc** [comment]
@daveb-501commons - The CLI NPE bug was fixed [here](https://github.com/forcedotcom/dataloader/commit/392159a559b4fc1d1a2bea5599a9b385b96719dc) but it has not made out to production instances yet and it will be available from starting this weekend, next Monday (March 25th) at the latest. However, updated Data Loader v45 with the fix is already available from [here](https://github.com/forcedotcom/dataloader/releases/tag/v45.0.0). Although the version looks the same, attached files are actually updated with the fix.

@alina133 - If you are still having problems with the latest from [here](https://github.com/forcedotcom/dataloader/releases/tag/v45.0.0) , could you share your reproducible steps with config, process files if possible.

**Comment by xbiansf** [comment]
The github release section should have the latest built Jars.   I tried it and it worked from my test.

**Comment by daveb-501commons** [comment]
Issue fixed with the latest release drop - thanks

**Comment by jvolkov** [comment]
I'm seeing this in v48

**Comment by dkadam77** [comment]
same issue with v49 as well...Please fix it.

**Comment by dkadam77** [comment]
Is there any update??? Cannot use Data Loader due to the error.

**Comment by intlgirlofmystery** [comment]
Salesforce only supports DataLoader CLI for Windows.

**Comment by dkadam77** [comment]
I fixed the issue. This issue persists if you have multiple versions of Java. By default it Data Loader was picking up Oracle Java home and hence causing the issue. Pointed to use Zulu and it started working.

**Comment by laurengranada** [comment]
@dkadam77 Can you clarify where you pointed to use Zulu? I am running into the same problem on mac

**Comment by jvolkov** [comment]
@laurengranada 

It turned out I didn't have Zulu installed at all.  Assuming you're on Mac?  Try this.

1. Open Terminal
2. Type in `open /Library/Java/JavaVirtualMachines` (or just go there any old way)

Do you see Zulu there?
![image](https://user-images.githubusercontent.com/1066119/84727785-a9d27380-af44-11ea-899f-316fd6b7481b.png)

If not [go here](https://www.azul.com/downloads/zulu-community/?version=java-13&os=macos&architecture=x86-64-bit&package=jdk) and [install Zulu](https://docs.azul.com/zulu/zuludocs/ZuluUserGuide/InstallingZulu/InstallOnMacOSXUsingDMGPkgThroughGUI.htm).  It needs to be at least version 11 or higher.

**Comment by haripopuri** [comment]
I have both JDK 11 and Zulu 14. But my JAVA_HOME is pointing to JDK 11, which is causing NULL pointer exception.
I edited "dataloader.command" file to look for version 14 (Zulu) and it worked. Here is the line I edited

Old: export JAVA_HOME=$(/usr/libexec/java_home -v 11)

New: export JAVA_HOME=$(/usr/libexec/java_home -v 14)

**Comment by dkadam77** [comment]
I have started facing this issue again with DL v50 and new beta MacOs Big Sur ...I have configured the correct JAVA_HOME but still it throws the null pointer exception.
