### ISSUE TITLE
Login - Unsupported Browser

### ISSUE THREAD

**Issue by MattMet86** [forcedotcom/dataloader#196]
It appears that the login page is being rendered via Internet Explorer not matter what the local system default is set to use. I cannot login today as an update to IE11 is now resulting in an "Unsupported browser..." error message from Lightning. Is there a way to force Data Loader to render via Chrome instead? 
<img width="213" alt="2019-10-07_11-09-46" src="https://user-images.githubusercontent.com/56268813/66329723-97ebfb80-e8f4-11e9-954c-a2a778da9edc.png">

**Comment by Raghuramaalla** [comment]
Hey Matt

you found any workaround.

**Comment by fubfub** [comment]
I have the same issue. Some users were able to resolve by following the "supported browser" link, then closing the window, and login then worked on the second try. Didn't work for me though! I completely removed Internet Explorer from my system, although to no avail.

**Comment by ashitsalesforce** [comment]
Data Loader uses Eclipse SWT Browser widget to display the OAuth login page. [Eclipse SWT FAQ](https://www.eclipse.org/swt/faq.php#browserplatforms) on supported browsers has pointers on which browsers are used by default and how to change that using java system properties `org.eclipse.swt.browser.DefaultType` and `org.eclipse.swt.browser.IEVersion` (specific browser or browser version in case of IE). 

Note: You will need to set Java system properties using the environment variable `JAVA_TOOL_OPTIONS` because the dataloader.bat script does not support them when passed as command line arguments to the script.
