### ISSUE TITLE
Why does it  always ask for ZULu JDK not just  JDK  version

### ISSUE THREAD

**Issue by JFDu** [forcedotcom/dataloader#209]
Why does it  always ask for ZULu JDK not just  JDK  version.   Most of us have installed Open JDK or oracle JDK. The business users are not willing to install mutiple JDK on the system.

Could we help fix it only require the JDK version ?

**Comment by wherestheguac** [comment]
Agreed, the switch to Zulu JDK wasn’t a great idea. My entire team is stuck using v44

**Comment by happiness801** [comment]
I just modified the `dataloader.bat` file to look for '*openjdk*' instead of '*zulu*' because I can't imagine it would make a difference. So far, so good. I'll report back :)

**Comment by happiness801** [comment]
Yeah, FYI, it worked fine. Tested with v49 and v48. I just changed line 25 to:

```
for /F "delims=" %%a in ('powershell -Command "foreach($path in (Get-ChildItem Env:Path).value -split ';') { if($path -like '*openjdk*') { $jdkDir = $path -split 'bin\\' }}; echo $jdkDir"') do Set "ZULU_JAVA_HOME=%%a"
```

and line 34 to not automatically add '\bin' because the '\bin' part was already in my path.

And it works just fine. 

Here's my Java version:
```
C:\Users\username\dataloader\v48.0.0>java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

**Comment by pgumiela** [comment]
@ashitsalesforce, is there any chance to bring Oracle JDK back as a default?

**Comment by ashitsalesforce** [comment]
Hi @pgumiela ,

Data Loader requires JRE 11 or later. It does not have to be Zulu. It does not have to be JDK, JRE will suffice. So, as far as JRE version is 11 or later, it shouldn't matter if it is Zulu OpenJDK or Oracle JDK or Oracle JRE. The current dataloader.bat (for Windows) and dataloader.command (for Mac) scripts have the limitation that they check for Zulu OpenJDK instead of checking for JRE 11 or later.

This limitation will be addressed in the next release. The necessary [code change](https://github.com/forcedotcom/dataloader/blob/master/release/win/dataloader.bat) is already checked in. Note that dataloader.bat from the repo is templatized - pom.xml sets version-specific variable values.

The current check in dataloader.bat is checking for zulu in path:
`for /F "delims=" %%a in ('powershell -Command "foreach($path in (Get-ChildItem Env:Path).value -split ';') { if($path -like '*zulu*') { $jdkDir = $path -split 'bin\\' }}; echo $jdkDir"') do Set "ZULU_JAVA_HOME=%%a"
`
The next release's check in dataloader.bat will be checking for JRE v11 or later (MIN_JAVA_VERSION is set to 11 by pom.xml when generating the zip file):
`:CheckMinJRE
    echo Data Loader requires Java JRE %MIN_JAVA_VERSION% or later. Checking if it is installed...

    PATH=%PATH%;%JAVA_HOME%\bin\;%ZULU_JAVA_HOME%\bin\;

    java -version 1>nul 2>nul || (
        goto JavaErrorExit
    )

    for /f "tokens=3" %%a in ('java -version 2^>^&1 ^| findstr /i "version"') do (
        set JAVA_FULL_VERSION=%%a
    )
    set JAVA_FULL_VERSION=%JAVA_FULL_VERSION:"=%

    for /f "tokens=1 delims=." %%m in ("%JAVA_FULL_VERSION%") do (
        set /A JAVA_MAJOR_VERSION=%%m
    )

    if %JAVA_MAJOR_VERSION% LSS %MIN_JAVA_VERSION% (
        goto JavaVersionErrorExit
    )
`

**Comment by ashitsalesforce** [comment]
Closing the issue.
