### ISSUE TITLE
With Dataloader, incorrect rows displayed in the Success file when an Insert fails with a "Failed to parse date" error

### ISSUE THREAD

**Issue by gvpatel** [forcedotcom/dataloader#230]
Hi - Does anyone has solution to this issue - Reference W-4273711 

With Dataloader, incorrect rows displayed in the Success file when an Insert fails with a "Failed to parse date" error

https://trailblazer.salesforce.com/issues_view?id=a1p3A000000mCGXQA2

**Comment by ashitsalesforce** [comment]
Closing the issue as the fix is checked in. It will be available with the next build of data loader, which likely will be v52.

**Comment by gvpatel** [comment]
Thanks ashitsalesforce. Really appreciate it.

**Comment by hanuma1111** [comment]
Hi,
This Issue is not fixed and still facing the same issue with 52 and 54 versions as well.
I have attached the Success and Error files where you can see Error Records are present in Success Table and also, Success Sheet with incorrect data like Customer Class/Cusotmer Sub Class are Required fields for every Account, where as some records with blank or #NA values records are showing in Success sheet without any error.

When you check the Error sheet, error message is incorrect for every record it is showing, where as the data is present.

It's like Error records are swapping into Success Table and also error message also swapped.

Could you please help us to resolve this issue as it is High priority for the Business, because when we generate reports on Transaction History Object for Error Records to trouble shoot, its Miss-Leading.

[LNaccountUpsertError20220301-171824.csv](https://github.com/forcedotcom/dataloader/files/8166495/LNaccountUpsertError20220301-171824.csv)
[LNaccountUpsertSuccess20220301-171824.csv](https://github.com/forcedotcom/dataloader/files/8166496/LNaccountUpsertSuccess20220301-171824.csv)

**Comment by hanuma1111** [comment]
I have created another Issue 436 for the same issue as it is closed, if possible, could you please take a look and provide your inputs which will help to resolve the issue.

https://github.com/forcedotcom/dataloader/issues/436
