### ISSUE TITLE
Maven deps broken

### ISSUE THREAD

**Issue by thiakil** [forcedotcom/dataloader#244]
It seems d11d6cb4 broke things - perhaps someone forgot to commit the artifacts to the local repo in the tree?

https://github.com/forcedotcom/dataloader/blob/afda769be87da90504c76db6aea12fd13dab1264/pom.xml#L403-L407

**Comment by ashitsalesforce** [comment]
Hi thiakil,

The change is to use the SWT package from a local maven repo instead of pointing to a public repo. This is to enable picking up the latest SWT jar when needed. Here are the commands you may want to use for adding SWT jars to your local maven repo:

Download the latest SWT jar from eclipse downloads page: https://download.eclipse.org/eclipse/downloads/index.html#Latest_Release 

Run 
mvn install:install-file -Dfile=<jar file name> -DgroupId=<group ID specified in pom.xml> -DartifactId=<artifactId specified in pom.xml. -Dversion=<version of the downloaded jar> 
-Dpackaging=jar

Optionally specify path to the local maven repo for DL. Do this only for jars that you want to push to the maven repo for DL:
-Dmaven.repo.local=<path to local maven repo for DL>

For example, 
mvn install:install-file -Dfile=swt.jar -DgroupId=local.swt -DartifactId=swtmac -Dversion=4.18 -Dpackaging=jar

And 

mvn install:install-file -Dfile=swt.jar -DgroupId=local.swt -DartifactId=swtwin -Dversion=4.18 -Dpackaging=jar

**Comment by thiakil** [comment]
Thanks for the info.

Perhaps the build section of the readme should be updated?

**Comment by ashitsalesforce** [comment]
Hi thiakil,

That's a good point. On other hand we may include SWT as part of the project. Will make one of these changes soon.

Thanks.

**Comment by ashitsalesforce** [comment]
Hi thiakil,

I have included the right version of SWT in the repo. This should fix the issue.

**Comment by thiakil** [comment]
That does seem to work
