### ISSUE TITLE
[Feature Request] Further improvements regarding Object Search mechanism

### ISSUE THREAD

**Issue by pgumiela** [forcedotcom/dataloader#272]
This FR is a continuation of #261.

It would be great to consider the following improvements:
- the ability to search both by Label or API Name (currently it works only for API Name)
- narrow down search results immediately, without the need to press any keys
- add support for wildcard characters (such as \*) to make the search easier (like Acc*)

**Comment by ashitsalesforce** [comment]
Added the following improvements:
- the ability to search both by Label or API Name (currently it works only for API Name)
- narrow down search results immediately, without the need to press any keys

These will be available in the next release of the data loader. Did not add wildcard characters because the search looks for the pattern match rather than exact match.
