### ISSUE TITLE
allow customers to specify a different JRE for data loader

### ISSUE THREAD

**Issue by ashitsalesforce** [forcedotcom/dataloader#372]
Per comments [here](https://github.com/forcedotcom/dataloader/pull/252#issuecomment-995865949), some customers need to use a different version of JRE for data loader than the system default. Data Loader should support setting of an environment variable or a property that allows for specifying it without changing the system default.

**Comment by bgaspic** [comment]
Hi @ashitsalesforce,
Thanks for adding this.
Some versions prior, there had been an approach used in `dataloader.bat` -- but not in `process.bat` -- to do
`for /F "delims=" %%a in ('powershell -Command "foreach($path in (Get-ChildItem Env:Path).value -split ';') { if($path -like '*zulu*') { $jdkDir = $path -split 'bin\\' }}; echo $jdkDir"') do Set "ZULU_JAVA_HOME=%%a"`
 and then to check for `ZULU_JAVA_HOME`.
This had basically worked out, because it did not matter (to `dataloader.bat`) whether the first Java in the path was Oracle's Java 8 -- it would find the Zulu if it existed, and used it. (the `process.bat`, for some reason, did not do the same, and then it got "stuck" on the Oracle Java 8)
I agree that setting `DATALOADER_JAVA_HOME` is more clean, and now `process.bat` and `dataloader.bat` use it in the exact same way.

**Comment by ashitsalesforce** [comment]
Hi @bgaspic , as you correctly observed, DATALOADER_JAVA_HOME setting is clearner because ZULU_JAVA_HOME indicated that Data Loader requires a Zulu JRE, which is incorrect. Worse yet, the code also checked for zulu installation, which too was incorrect. Data Loader requires a JRE (Oracle, Zulu, ...) version 11 or later.
