### ISSUE TITLE
Error: Main method not found in class com.salesforce.dataloader.process.ProcessRunner with the new release V53.0.2

### ISSUE THREAD

**Issue by miguelartiaga** [forcedotcom/dataloader#381]
I have just to replace the dataloader-51.0.1-uber.jar with the dataloader-53.0.1-uber.jar from the V53.0.2 due to the log4j vulnerability and I am getting the error:
Error: Main method not found in class com.salesforce.dataloader.process.ProcessRunner, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application
Any idea how can I solve it?
Thanks

**Comment by ashitsalesforce** [comment]
Hi @miguelartiaga, data loader now has only one main method in DataLoaderRunner.java. It supports both GUI and batch mode. You should invoke it with `run.mode=batch` argument in your script as the replacement to specifying ProcessRunner.

**Comment by PrafulGuptaDarta** [comment]
![CMD](https://user-images.githubusercontent.com/83292787/147111617-29c1734c-ca5f-406e-b94b-30e1bb9f9ab3.PNG)
attached is the error I'm seeing with a recent version of data loader using via CLI, any idea how to fix this?

**Comment by ashitsalesforce** [comment]
Hi @PrafulGuptaDarta , based on the error messages you have provided, it is likely that you are using Spring 1.x syntax in your config XML file (the one you have marked out), likely because it uses the syntax "singleton=true" or "singleton=false" in line 5 of the file instead of Spring 2.x syntax scope="prototype".

Look at sample xml files in samples\conf for the correct use of Spring 2.x syntax.
