### ISSUE TITLE
Tool cannot be packaged after version 53

### ISSUE THREAD

**Issue by MaxG-Enpal** [forcedotcom/dataloader#397]
After version 53
The tool gives the error: Unable to find SWT jar for Windows 10 : amd64 after it's packaged with jpackage

Is it possible to get the version 52 with the log4j fixes?
Or, How can I package version 53.0.2 with jpackage?

OP: "Windows 11"
OP Version: "21H2"
Java:
"openjdk 17.0.1 2021-10-19 LTS
OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing)"

**Comment by ashitsalesforce** [comment]
Hi @MaxG-Enpal, we support Windows 10 in version v53.0.2. So, it is likely an issue with the installation mechanism you are using, which is different than the documented and supported installation steps. While we do not support installations done in ways other than documented installation steps, you are likely encountering an issue where v53.0.2 implementation looks for SWT jars in the directory it is launched from rather than the directory in which dataloader-53.0.2-uber.jar is installed. This was fixed subsequently (fix is already checked in) and will be made available with the next release of data loader.

**Comment by MaxG-Enpal** [comment]
> Hi @MaxG-Enpal, we support Windows 10 in version v53.0.2. So, it is likely an issue with the installation mechanism you are using, which is different than the documented and supported installation steps. While we do not support installations done in ways other than documented installation steps, you are likely encountering an issue where v53.0.2 implementation looks for SWT jars in the directory it is launched from rather than the directory in which dataloader-53.0.2-uber.jar is installed. This was fixed subsequently (fix is already checked in) and will be made available with the next release of data loader.

Thank you so much :)
That’s exactly the problem!
I’m gonna check it next year (next week) and close this issue afterwards.

**Comment by ashitsalesforce** [comment]
Sounds good. FWIW, the pull request containing the fix is PR #388 .

**Comment by ashitsalesforce** [comment]
v53.0.3 is released. It contains the fix for this issue.
