### ISSUE TITLE
SSO Login fails with dataloader opened through the .bat

### ISSUE THREAD

**Issue by gulinski-krystian** [forcedotcom/dataloader#410]
Versions: v52+
Platform: Windows
SSO provider: PingIdentity
java: zulu11

So the issue appears when you open dataloader through the batch file, which most users who installed the dataloader will use.

Steps:
1. Click on any action
2. Prompt the OAuth login (any env)
3. Webview pops up, you follow the flow and use the SSO
4. After you finish logging in the last redirect doesn't work properly and it gets stuck at the screen attached.
5. If you close the window and attempt to log in again it will work, so only the first login gets stuck

Important note: Issue doesn't happen if you open dataloader directly through the .jar file

---

Tried opening from cmd and it seems like the option added in the batch file is causing this.
`-D"org.eclipse.swt.browser.IEVersion=12001"`
If i remove the option it's working as expected.

![image](https://user-images.githubusercontent.com/73952595/149515403-e160bce2-cdd7-4d20-84ef-b7cc7157c933.png)

**Comment by ashitsalesforce** [comment]
Hi @gulinski-krystian , the java system property org.eclipse.swt.browser.IEVersion is set to 12001 so that SWT uses Edge HTML engine in its Browser widget, which is used by Data Loader when OAuth login is selected. 

If this system property is not set, the default value used by SWT is IE 11. Salesforce has stopped supporting IE 11 - see [announcement](https://help.salesforce.com/s/articleView?id=release-notes.rn_supported_browsers_ie11.htm&language=en_US&r=https%3A%2F%2Fwww.google.com%2F&release=230&type=5). Not setting this system property had resulted in issues #242 and #196 when OAuth provider is Salesforce. Given that you had to switch to the default value for your OAuth provider, PingIdentity, wondering if their OAuth client-side javascript does not work on Edge browser.

**Comment by ashitsalesforce** [comment]
Hi @gulinski-krystian , -skipieversion is added to dataloader.bat to skip setting of org.eclipse.swt.browser.IEVersion. This should address your issue.

**Comment by ashitsalesforce** [comment]
The checked in fix will let an explicit setting of org.eclipse.swt.browser.IEVersion system property override the default value of 12001. Set JAVA_TOOL_OPTIONS environment variable to the desired value. For example, set JAVA_TOOL_OPTIONS to "-Dorg.eclipse.swt.browser.IEVersion=11001" if IE browser instead of Edge browser is desired.

**Comment by gulinski-krystian** [comment]
Haven't had issues with Edge and PingIdentity. Also tons of people use it daily.
Only had issues with the webview inside DataLoader

Do we have any proof that this webview actually launches in edge mode with 12001 defined?
As I mentioned it doesn't pop up in any official documentation, so I'm still not sure whether its valid

**Comment by gulinski-krystian** [comment]
I still get the issue on master.
Anything I could verify on the PingIdentity side of things? I checked it with Edge and it works fine

**Comment by ashitsalesforce** [comment]
Hi @gulinski-krystian , per my previous comments, fixing issues #242 and #197 required explicitly setting org.eclipse.swt.browser.IEVersion=12001 in dataloader.bat. [Here](https://www.eclipse.org/swt/faq.php#browserplatforms) is Eclipse SWT documentation on the supported and default browser platforms. These are the 2 supporting evidences that Eclipse SWT Browser widget uses Edge mode when org.eclipse.swt.browser.IEVersion is set to 12001.

Regarding your issue persisting on master, what did you do? Sync to main and built Data Loader? Your pull request indicated that you had success with v53.0.3 of Data Loader after removing -Dorg.eclipse.swt.browser.IEVersion=12001 from dataloader.bat. Is that still the case?

**Comment by gulinski-krystian** [comment]
Yeah, essentially falling back to the default (11001) by not providing the option or providing it explicitly was helping.

I think I found the problem though - the 12001 isn't launching edge.
I managed to get the webview to launch using edge using this option
`java -D"org.eclipse.swt.browser.DefaultType=edge" -jar .\dataloader-54.0.0-uber.jar`

Maybe you can look into this being added to the `dataloader.bat` for windows releases
I believe this 12001 option for `org.eclipse.swt.browser.IEVersion` is just doing something entirely else.
The one above (`org.eclipse.swt.browser.DefaultType`) actually launches the edge webview (can be easily noticed by an icon appearing when typing a password that appears only for edge).

**Comment by ashitsalesforce** [comment]
Hi @gulinski-krystian , thanks for this troubleshooting help. Which Windows version are you using? Asking because making the change to use "edge" as the default value instead of "12001" may break Data Loader OAuth for some other customers that use older Windows.

The latest checked in code will support the following behavior in the future releases:
If JAVA_TOOL_OPTIONS environment variable contains a value for "org.eclipse.swt.browser.DefaultType" property, it will override the default "12001". So, if you set JAVA_TOOL_OPTIONS to the value "-Dorg.eclipse.swt.browser.DefaultType=edge", it will work for your use-cases.

**Comment by gulinski-krystian** [comment]
Yeah, I know it can be mitigated with this env var, but I'd love to have it working by default, so that there's no additional deployment steps to user devices.

My windows version is 21H2, so newest:
![image](https://user-images.githubusercontent.com/73952595/149899041-2cf91adc-688a-49a8-93d5-3b502cffdfe2.png)

I actually wonder what "12001" is doing on the older windows versions you mentioned.
On mine it doesn't launch edge - it looks like IE, but probably not the version that 11001 is launching (because 11001 is working fine for me with PingIdentity and 12001 isn't).

Maybe the older versions will benefit from using the "edge" option as well and the issues raised by other customers can still be covered.
I checked and it seems windows versions >= 19H1 should have edge deployed.

**Comment by ashitsalesforce** [comment]
Hi @gulinski-krystian , these are good points and thanks for providing further details on Edge support. Seems that the best course seems to be to remove all explicit configuration of either "org.eclipse.swt.browser.DefaultType" or "org.eclipse.swt.browser.IEVersion" and let SWT pick the default. This would result in Edge browser engine used by SWT version 4.19 or later per [SWT FAQ](https://www.eclipse.org/swt/faq.php).  If a customer wants to specify IE browser, they can set JAVA_TOOL_OPTIONS environment variable with the value "-D"org.eclipse.swt.browser.DefaultType=ie".

**Comment by gulinski-krystian** [comment]
Hey, I checked the recent master version and it's working well for me, but I'm quite sure it's not edge launching by default on my windows config (it's probably IE 11001). I can observe differences in behavior and look when explicitly setting edge.

So the design decision right now is to use the SWT default (even if it's IE on windows)?
Overall I have no issues with the default SWT browser mode. 
Normal SF login with MFA works well and I assume the previous issues should still be resolved.
dataloader has been using IE all this time, so I guess the current behavior is ok

But you specifically mentioned that you want edge to be the default, so that's why I'm raising this observation

**Comment by ashitsalesforce** [comment]
Hi @gulinski-krystian , our developers haven't been able to distinguish among browser engines (edge or IE) when authenticating through Salesforce OAuth IdP. So, the fact that removal of explicit setting of "org.eclipse.swt.browser.IEVersion" fixed your issue and did not resurface the issues encountered in the past when using Salesforce OAuth is the right choice instead of explicitly setting "org.eclipse.swt.browser.DefaultType" to Edge. Using the default gives customers ability to override it if needed.

Thanks again for going through nuances of this issue and verifying that MFA also works with SWT default browser setting.

**Comment by gulinski-krystian** [comment]
Ok, all clear. Great to hear that!

Do you have an idea when and if this can be included in a patch release to v53?

**Comment by gulinski-krystian** [comment]
Is there any chance of backporting it to v53 and v54?
I'm trying to have the users upgrade their dataloader to a version with an updated log4j, but this authentication issue was kind of a blocker.
I can always prepare a custom build for them, but that's more makeshift

**Comment by ashitsalesforce** [comment]
Hi @gulinski-krystian , there is a small chance of a backport into v54 if a critical issue surfaces that requires patching v54.0.0.

**Comment by techforecastis** [comment]
Started running into this issue on Windows 10 in relationship to org instances that were using Login Flows. with no environment variables set it went to IE11 and didn't work, when trying to the IE version variable, it also didn't work. The only fix I was able to get was by setting these environment variables for version 53.0.2 (latest cleared through security by our IT people)

Variable Name: JAVA_TOOL_OPTIONS
Variable Value: Dorg.eclipse.swt.browser.DefaultType=edge,chromium

This worked on machines that had Edge as default browser, or those that had some chrome variant installed.

**Comment by ashitsalesforce** [comment]
Hi @techforecastis , thanks for providing an informative comment regarding how to address this issue on certain deployments.
