### ISSUE TITLE
Cannot download dataloader

### ISSUE THREAD

**Issue by cella5831** [forcedotcom/dataloader#600]
I have downloaded Zulu19 and the dataloader zip for windows but it keeps failing. It will not create a shortcut or desktop icon and just quits installation. Can anyone get on a call and help me?

**Comment by ashitsalesforce** [comment]
Hi @cella5831 , did you follow [installation steps](https://developer.salesforce.com/docs/atlas.en-us.dataLoader.meta/dataLoader/loader_install_windows.htm)? If so, have you extracted the data loader zip file contents as described in step 5? If so, which version of data loader are you trying to install? Also, capture the screenshot of the command window as you go through the installation steps and share if possible so that we can further troubleshoot the issue.

**Comment by cella5831** [comment]
Yes i followed install steps. I am trying to get the latest version. https://www.loom.com/share/4ef404032e4549c883d183b6c5b7fc18

**Comment by ashitsalesforce** [comment]
Hi @cella5831 , thanks for these details. The issue seems to be that data loader installation script is unable to create a file named `dataloader.lnk` in your `Desktop` folder, likely due to inadequate permissions.

**Comment by cella5831** [comment]
Thank you! I figured it out
