### ISSUE TITLE
Export only allows comma separator

### ISSUE THREAD

**Issue by johnguem** [forcedotcom/dataloader#723]
**Describe the bug**
When generating an export operation the system is only taking the comma as separator even when the 'Allow other characters as CSV delimiters' had been checked in the settings option

**To Reproduce**
1. Go to Settings
2. Click on 'Allow other characters as CSV delimiters' and fulfill the "Other delimiters" with a '-' character
3. Scroll down and press the button to apply changes
4. Click in the 'Export' option and export two or more columns of any object
5. In the result file you will see the file is always generated with columns separated with the comma character

**Expected behavior**
The result file should be generated with the character defined in the settings.

**Screenshots**
![image](https://github.com/forcedotcom/dataloader/assets/61925965/6840fe79-5b07-4e6e-8d55-9a45bbbdc188)

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Version 48.0.0

**Additional context**

**Comment by ashitsalesforce** [comment]
Hi @johnguem , Data Loader currently allows delimiters other than comma char for upload operations. The settings are for alternate delimiters during upload operations, not extract operations. It uses comma char for extract operations and there is no way to specify an alternate delimiter. 

The wording 'Allow other characters as CSV delimiters' is ambiguous because it does not specify whether is it applicable to uploads, extracts, or both.

**Comment by ashitsalesforce** [comment]
Closing it as the fix is checked in. It will be available in the next patch or major release.
