### ISSUE TITLE
Log file doesn't represent accurately uploaded records

### ISSUE THREAD

**Issue by ophirpeleg** [forcedotcom/dataloader#984]
**Describe the bug**
I've uploaded attachments, I got an error on one of the files and two log files (error and success).
On the error file appears one record, the same record appears on the success file as "CREATED ITEM", with an ID. 
I've tried to access this ID, and it's leading to the file below (below = the record below in the CSV file) 

**To Reproduce**
Upload a file with file extension :".xtas" 

**Expected behavior**
I would expect to find only one time the record. 

**Screenshots**
![image](https://github.com/forcedotcom/dataloader/assets/20849077/1678e4c8-a976-4c00-aa40-8a14077f55e2)

**Desktop (please complete the following information):**
 - OS:Windows 11 
 - Version: V60

**Comment by ashitsalesforce** [comment]
Hi @ophirpeleg , 

Can you share content of config.properties file (remove personal and business sensitive information)?

**Comment by ophirpeleg** [comment]
Hi @ashitsalesforce, 
Sure, attached
[config - Copy.txt](https://github.com/forcedotcom/dataloader/files/14283698/config.-.Copy.txt)
change file extension to txt in order to upload to Github

**Comment by ashitsalesforce** [comment]
Thanks @ophirpeleg . One more question: how many records are you uploading?

**Comment by ophirpeleg** [comment]
Hi @ashitsalesforce,
I was uploading 100 files

**Comment by ashitsalesforce** [comment]
Hi @ophirpeleg, 

Does that mean 100 rows in the CSV file? I ask because we have recently seen an issue where incorrect row shows up in success file if "use Bulk API" is false and number of records to be uploaded is greater than batch size. In your case "use Bulk API" is false. However, your batch size is 200 and your number of records to be uploaded seems to be 100.

Perhaps you can try by enabling "use Bulk API" in Advanced Properties dialog. If it works, it is likely that you are encountering the same issue.

**Comment by ashitsalesforce** [comment]
@ophirpeleg , [v60.0.1](https://github.com/forcedotcom/dataloader/releases/tag/v60.0.1) containing the fix is released. Let us know if that works.
